# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test(self):
    self.driver.get("http://localhost:8080/LMS/")
    self.driver.set_window_size(790, 438)
    self.driver.find_element(By.NAME, "user_name").send_keys("j")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("j")
    self.driver.find_element(By.NAME, "signin").click()
    self.driver.find_element(By.LINK_TEXT, "Book").click()
    self.driver.find_element(By.LINK_TEXT, "View All Books").click()
    self.driver.find_element(By.LINK_TEXT, "Search Book").click()
    self.driver.find_element(By.ID, "search").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) .btn")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "search").send_keys("asd")
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) .btn").click()
  
