# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test123():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_123(self):
    self.driver.get("http://localhost:8080/LMS/")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.NAME, "user_name").send_keys("j")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("j")
    self.driver.find_element(By.NAME, "signin").click()
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) span").click()
    self.driver.find_element(By.NAME, "author_name").click()
    self.driver.find_element(By.NAME, "author_name").send_keys("asd")
    self.driver.find_element(By.NAME, "profile").click()
    self.driver.find_element(By.NAME, "profile").send_keys("qwerty")
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) .btn").click()
  
